dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: yzZVoRHQodg/bjK0g39lfEUsBAGLbUOssll9NiJKzikLnY/2D/CUM/vx9ogXeqYmaTvBPPX2832Oxty632XxU0UAiv5y1Q7TSiHdy2QfscDdJVKL+MFg2uiImV+OvkxgDQchk5yjkieLDQ/zBUPXgbtpD6RwJSjRI8kkoo2A6MzqArn0y3lGO84SPc3Nqd2Kzz+ZL0dN4CAOqhDIEdy0ZrfLUEmF9XlOevkg47knftArH/f7erFd/U4+SdkOeP5J+U1N4eRW56btkYVtDcCjJwxoIuGBr3ehjyjm/KV4buNY5zy8rY9I4G/QeFXoahh3ZpCrvERu4tsLQBF6vZo7G/ELq7s4Vn4lOkEDuiWt65In+qhZNVkOu7hoC+Gh7HagkU/mol6HuUyjL3IkAMJGfqXLYa9lO4lyMlwlM+b5JkD+mr9BGmz42TqpUe/egRUIneVRtatDVSK0ZSvjZ69os5axyIrym7TByvFvPdpsKvKcgRQqQePv7oF8zuX5N5tI2qtizRUu8KqJbj+dkg29C70Or4f3Xds4lhLews9tbC/UKCwBpgTRYeBim2hIa+KbyrvvVrfdoYhfX6cE/sQgi8B0Xrn4KfpoJyTmq0X+Uha7ndJhgAJg4Ef/DqbS+UQ9mxAl1Vl/ksCKzoS4wNYmZ63VQYH9aDJj5BHCaVcZuVk=
  app: "$APP"
