dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: Ep4DATbkxKe965EzzF3mfqOmU6ebwAdZLdJ+LGXLb77KE7myLpctJHKd2Qoxv0Dfz3SUwSFXJK1X1Z26vipACpqF9iQviOYt4hzry6m1cJ7sYx0KZ7SfNXUWfDbBcb/5OrKPao3lPGMHC3AXKXttJXLZAjn6vtTD5LPBET1pVULGQhO0jJrKCw3UIk6pKzFOZN74k+qKks1OBO8HmBWOVkFAb0hqacV3QxqGkeGi6dWPqU9Amvqm0lEHm9UrS72mtidXCox0m+/gzV88ODlHDNV6JDZvjfG5ptG2wv/4LpB8c9nJdQ7A5eEAZnunv4PwC0hKB8z6/SbPWxiwzZprw8I/9fi9CNvOL4sAFIj06muUnwBkJ0xnEzwFfUPhubdXW4ZgSCXGcWAkSQHDGcvVadrM9hazkTK6m5wIFjx+jOU5cBd6JKebLcNcD3kD9CY4CmjkOzyi5/z19CsSEbN6NMC3VhgUNQQCncBncybCgzp5CdfgZzmICo+Hmjfsi69bZfxkKFZdFEbrzddcPkDMzZh0FbFUvqvLDOxyo6ytSP0a8ZrTS2MaYv/2WsfMWBfuc8htiZjaLJSgV0gtIFO8AqPfWLRk/vrYJc7FL2+Jon9DrHtQn3ngTdR/UjMGs/DGT+Q1n3wr0NImTlbc0PT6VRnvqmvjFKwjzJUVEQd9W1c=
  app: "$APP"
